interface FlagsObject {
  [key: string]: string;
}

export const flags: FlagsObject = {
  qatar: "🇶🇦",
  ecuador: "🇪🇨",
  senegal: "🇸🇳",
  netherlands: "🇳🇱",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  iran: "🇮🇷",
  usa: "🇺🇸",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  mexico: "🇲🇽",
  poland: "🇵🇱",
  argentina: "🇦🇷",
  saudi_arabia: "🇸🇦",
  france: "🇫🇷",
  australia: "🇦🇺",
  denmark: "🇩🇰",
  tunisia: "🇹🇳",
  germany: "🇩🇪",
  japan: "🇯🇵",
  spain: "🇪🇸",
  costa_rica: "🇨🇷",
  belgium: "🇧🇪",
  canada: "🇨🇦",
  morocco: "🇲🇦",
  croatia: "🇭🇷",
  brazil: "🇧🇷",
  serbia: "🇷🇸",
  switzerland: "🇨🇭",
  cameroon: "🇨🇲",
  portugal: "🇵🇹",
  ghana: "🇬🇭",
  uruguay: "🇺🇾",
  south_korea: "🇰🇷",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  hungary: "🇭🇺",
  italy: "🇮🇹",
  albania: "🇦🇱",
  slovenia: "🇸🇮",
  austria: "🇦🇹",
  slovakia: "🇸🇰",
  romania: "🇷🇴",
  turkey: "🇹🇷",
  czech_republic: "🇨🇿",
  ukraine: "🇺🇦",
  georgia: "🇬🇪",
};
